// Generated by tool/build_i18n.py from languages.json. Do not edit.
const uiLanguageNames = <String, String>{
  "zh": "简体中文",
  "en": "English",
  "ru": "Русский",
  "fr": "Français",
  "de": "Deutsch",
  "es": "Español",
  "ja": "日本語",
  "ko": "한국어",
  "pt": "Português",
};
const uiFallbackLocale = "zh";
const uiSystemFallbackLocale = "en";
bool isUiLocale(String value) => value == 'system' || uiLanguageNames.containsKey(value);
