//! Experimental managed carrier for host-selected immutable file bytes.
//! This is a single-frame read/finish/cancel profile, not an OS picker, durable
//! evidence store, general IO handler ABI, filesystem path API or network backend.
use crate::{
    Fault, Report,
    io_binding::{self, IoBinding, IoResourceLease},
    manager::{ManagedInstance, Manager},
};
use morrow_core::{
    dispatch::HostRuntime,
    io::{Action, MAX_PAYLOAD_BYTES, Request, Response, Status},
    plugin_package::io::IoCapability,
};
use std::collections::BTreeMap;

const MAX_RESOURCES: usize = 128;
const MAX_SPOOL_BYTES: u64 = 256 * 1024 * 1024;
struct File {
    lease: IoResourceLease,
    bytes: Vec<u8>,
}
/// One trusted-host spool. Instance budgets are shared across bindings and brokers;
/// the additional resident-byte cap applies to this broker, not the whole process.
pub struct FileBroker {
    secret: [u8; 32],
    sequence: u64,
    files: BTreeMap<[u8; 32], File>,
}
pub struct FileIoReport {
    pub execution: Report,
    pub response: Option<Response>,
}
fn status(error: io_binding::Error) -> Status {
    match error {
        io_binding::Error::Expired => Status::Expired,
        io_binding::Error::Limit => Status::Quota,
        io_binding::Error::Denied => Status::Denied,
        io_binding::Error::Clock => Status::Denied,
    }
}
fn failure(request: &Request, value: Status) -> morrow_core::Result<Vec<u8>> {
    Response::encode(request, value, &[], 0, true)
}
impl FileBroker {
    /// Secret must be generated by the trusted host per broker; never accept it from a guest.
    pub fn new(secret: [u8; 32]) -> Self {
        Self {
            secret,
            sequence: 0,
            files: BTreeMap::new(),
        }
    }
    pub fn usage(&self) -> (usize, u64) {
        (
            self.files.len(),
            self.files.values().map(|f| f.bytes.len() as u64).sum(),
        )
    }
    /// Host maintenance must call this while idle to promptly release expired spools.
    pub fn reap(&mut self, now: u64) {
        self.files.retain(|_, f| !f.lease.reclaimable(now));
    }
    #[allow(clippy::too_many_arguments)]
    pub fn grant_file(
        &mut self,
        manager: &Manager,
        host: &HostRuntime,
        instance: &ManagedInstance,
        binding: &IoBinding,
        bytes: Vec<u8>,
        now: u64,
    ) -> io_binding::Result<[u8; 32]> {
        binding.preflight_capability(manager, host, instance, IoCapability::FileRead, now)?;
        self.reap(now);
        let (count, used) = self.usage();
        if count >= MAX_RESOURCES
            || used
                .checked_add(bytes.len() as u64)
                .is_none_or(|n| n > MAX_SPOOL_BYTES)
        {
            return Err(io_binding::Error::Limit);
        }
        let next = self
            .sequence
            .checked_add(1)
            .ok_or(io_binding::Error::Limit)?;
        let mut seed = b"morrow.selected-file.v1".to_vec();
        seed.extend_from_slice(&self.secret);
        seed.extend_from_slice(&next.to_le_bytes());
        let token = morrow_core::runtime::schema_digest(&seed);
        if self.files.contains_key(&token) {
            return Err(io_binding::Error::Limit);
        }
        let lease = binding.admit(
            manager,
            host,
            instance,
            IoCapability::FileRead,
            1,
            bytes.len() as u64,
            now,
        )?;
        lease.check(manager, host, instance, now)?;
        self.sequence = next;
        self.files.insert(
            token,
            File {
                lease: lease.into_resource(),
                bytes,
            },
        );
        Ok(token)
    }
    #[allow(clippy::too_many_arguments)]
    pub fn exchange(
        &mut self,
        manager: &Manager,
        host: &HostRuntime,
        instance: &ManagedInstance,
        binding: &IoBinding,
        request: &Request,
        now: u64,
    ) -> morrow_core::Result<Vec<u8>> {
        if let Err(e) = binding.preflight(manager, host, instance, now) {
            return failure(request, status(e));
        }
        let token = match request.action() {
            Action::Read { reference, .. }
            | Action::Finish { reference }
            | Action::Cancel { reference } => *reference,
            Action::SubmitHttp(_) | Action::Unsupported(_) => {
                return failure(request, Status::Unsupported);
            }
        };
        let Some(file) = self.files.get(&token) else {
            return failure(request, Status::NotFound);
        };
        if let Err(e) = file.lease.preflight(manager, host, instance, now) {
            return failure(request, status(e));
        }
        let (offset, payload, eof, release) = match request.action() {
            Action::Read { offset, limit, .. } => {
                let Ok(start) = usize::try_from(*offset) else {
                    return failure(request, Status::Failed);
                };
                if start > file.bytes.len() {
                    return failure(request, Status::Failed);
                }
                let count = if *limit == 0 {
                    MAX_PAYLOAD_BYTES
                } else {
                    *limit as usize
                };
                let end = start.saturating_add(count).min(file.bytes.len());
                (
                    *offset,
                    &file.bytes[start..end],
                    end == file.bytes.len(),
                    false,
                )
            }
            _ => (0, &[][..], true, true),
        };
        let response = Response::encode(request, Status::Completed, payload, offset, eof)?;
        let charged = (request.bytes().len() as u64)
            .checked_add(response.len() as u64)
            .ok_or(morrow_core::Error::Limit)?;
        let job = match binding.admit(
            manager,
            host,
            instance,
            IoCapability::FileRead,
            0,
            charged,
            now,
        ) {
            Ok(v) => v,
            Err(e) => return failure(request, status(e)),
        };
        if let Err(e) = job
            .check(manager, host, instance, now)
            .and_then(|_| file.lease.check(manager, host, instance, now))
        {
            return failure(request, status(e));
        }
        if release {
            self.files.remove(&token);
        }
        Ok(response)
    }
    /// Execute one exact IO frame through a declared independent IO handler. The guest
    /// must call IO once and complete with that exact broker response; no core effects.
    #[allow(clippy::too_many_arguments)]
    pub fn run(
        &mut self,
        manager: &Manager,
        host: &HostRuntime,
        instance: &ManagedInstance,
        binding: &IoBinding,
        handler: &str,
        request: &Request,
        mut clock: impl FnMut() -> u64,
    ) -> FileIoReport {
        let now = clock();
        let prepared = instance.package();
        let declared = prepared
            .package()
            .io_declaration()
            .is_some_and(|d| d.handlers.iter().any(|h| h == handler));
        if !declared || binding.preflight(manager, host, instance, now).is_err() {
            return FileIoReport {
                execution: Report {
                    outcome: Err(Fault::InactiveConnection),
                    host_calls: 0,
                    fuel_remaining: prepared.limits().fuel,
                },
                response: None,
            };
        }
        let token = match request.action() {
            Action::Read { reference, .. }
            | Action::Finish { reference }
            | Action::Cancel { reference } => Some(reference),
            Action::SubmitHttp(_) | Action::Unsupported(_) => None,
        };
        let guard = token
            .and_then(|key| self.files.get(key))
            .map(|f| f.lease.delivery_guard());
        let owns_resource = guard
            .as_ref()
            .is_some_and(|g| g.validate_identity(manager, host, instance).is_ok());
        let mut called = false;
        let mut protocol_fault = false;
        let mut actual = None;
        let run = prepared.run_file_frame(
            request.bytes(),
            &mut |input| {
                if called || input != request.bytes() {
                    protocol_fault = true;
                    return Err(());
                }
                called = true;
                let response = self
                    .exchange(manager, host, instance, binding, request, clock())
                    .map_err(|_| ())?;
                actual = Some(response.clone());
                Ok(response)
            },
            instance.cancellation(),
        );
        let mut execution = run.report;
        let after = clock();
        if called && owns_resource {
            self.reap(after);
        }
        let mut response = None;
        if execution.outcome.is_ok() {
            if binding.preflight(manager, host, instance, after).is_err()
                || guard
                    .as_ref()
                    .is_some_and(|g| g.preflight(manager, host, instance, after).is_err())
            {
                execution.outcome = Err(Fault::InactiveConnection);
            } else {
                match (run.completion, actual) {
                    (Some(done), Some(actual)) if !protocol_fault && called && done == actual => {
                        match Response::decode(request, &actual) {
                            Ok(value) => {
                                let delivery = if owns_resource {
                                    binding.check(manager, host, instance, after).and_then(|_| {
                                        guard
                                            .as_ref()
                                            .expect("owned resource guard")
                                            .check(manager, host, instance, after)
                                    })
                                } else {
                                    Ok(())
                                };
                                if delivery.is_ok() {
                                    response = Some(value);
                                } else {
                                    execution.outcome = Err(Fault::InactiveConnection);
                                }
                            }
                            Err(_) => execution.outcome = Err(Fault::TaskProtocol),
                        }
                    }
                    _ => execution.outcome = Err(Fault::TaskProtocol),
                }
            }
        }
        FileIoReport {
            execution,
            response,
        }
    }
}
