#define _CRT_SECURE_NO_WARNINGS
#include "morrow_blob_transfer_v1.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"FAIL %d %s\n",__LINE__,#x);exit(1);}}while(0)
typedef struct record{char*name;uint32_t ok,wn,kind,pl,status;uint64_t seq,offset,total;uint8_t hash[32],*payload,*wire;}record;
static uint32_t rd32(FILE*f){uint8_t b[4];CHECK(fread(b,1,4,f)==4);return(uint32_t)b[0]|((uint32_t)b[1]<<8)|((uint32_t)b[2]<<16)|((uint32_t)b[3]<<24);}
static uint64_t rd64(FILE*f){uint64_t lo=rd32(f),hi=rd32(f);return lo|(hi<<32);}
static void*alloc(size_t n){void*p=malloc(n?n:1);CHECK(p);return p;}
static record load(FILE*f){record r;uint32_t n=rd32(f);r.ok=rd32(f);r.wn=rd32(f);r.kind=rd32(f);r.pl=rd32(f);r.status=rd32(f);r.seq=rd64(f);r.offset=rd64(f);r.total=rd64(f);CHECK(rd64(f)==0);CHECK(n<256&&r.wn<=70000&&r.pl<=70000);CHECK(fread(r.hash,1,32,f)==32);r.name=(char*)alloc((size_t)n+1);r.payload=(uint8_t*)alloc(r.pl);r.wire=(uint8_t*)alloc(r.wn);CHECK(fread(r.name,1,n,f)==n);r.name[n]=0;CHECK(fread(r.payload,1,r.pl,f)==r.pl);CHECK(fread(r.wire,1,r.wn,f)==r.wn);return r;}
static void drop(record*r){free(r->name);free(r->payload);free(r->wire);}
static void fields(const mbt_view*v,const record*r){CHECK(v->abi_version==1&&v->struct_size==sizeof(*v)&&v->kind==r->kind&&v->reserved==0);for(int i=0;i<32;i++)CHECK(v->transfer_epoch[i]==1&&v->object_ref[i]==2&&v->operation_id[i]==3);if(r->kind==0||r->kind==3){CHECK(v->total_length==r->total&&memcmp(v->whole_sha256,r->hash,32)==0&&v->payload_length==0);}else{CHECK(v->sequence==r->seq&&v->offset==r->offset&&memcmp(v->chunk_sha256,r->hash,32)==0);if(r->kind==1)CHECK(v->payload_length==r->pl&&(r->pl==0||memcmp(v->payload,r->payload,r->pl)==0));else{CHECK(v->length==r->total&&v->status==r->status);for(int i=0;i<32;i++)CHECK(v->request_digest[i]==9);}}}
static void corpus(const char*input){FILE*f=fopen(input,"rb");CHECK(f);uint8_t magic[8];CHECK(fread(magic,1,8,f)==8&&memcmp(magic,"BLCV0001",8)==0);uint32_t n=rd32(f),accepted=0,rejected=0;for(uint32_t i=0;i<n;i++){record r=load(f);mbt_frame*h=(mbt_frame*)(uintptr_t)1;uint32_t rc=mbt_frame_decode(r.wire,r.wn,&h);if((rc==MBT_OK)!=(r.ok!=0)){fprintf(stderr,"VERDICT %s status=%u expected=%u\n",r.name,rc,r.ok);exit(1);}if(!r.ok){CHECK(h==(mbt_frame*)(uintptr_t)1);rejected++;}else{mbt_view v;CHECK(mbt_frame_view(h,&v,sizeof(v))==0);fields(&v,&r);memset(r.wire,0xaa,r.wn);fields(&v,&r);mbt_frame*assigned=NULL;CHECK(mbt_frame_set(&v,sizeof(v),&assigned)==0);uint8_t*out=(uint8_t*)alloc(65536);memset(out,0xa5,65536);uint32_t len=0xdeadbeef;CHECK(mbt_frame_encode(h,out,1,&len)==MBT_BUFFER&&len==0xdeadbeef&&out[0]==0xa5);CHECK(mbt_frame_encode(h,out,65536,&len)==0);for(uint32_t j=len;j<65536;j++)CHECK(out[j]==0xa5);mbt_frame*again=NULL;CHECK(mbt_frame_decode(out,len,&again)==0);mbt_view v2;CHECK(mbt_frame_view(again,&v2,sizeof(v2))==0);fields(&v2,&r);mbt_frame_free(h);CHECK(mbt_frame_view(assigned,&v2,sizeof(v2))==0);fields(&v2,&r);mbt_frame_free(assigned);mbt_frame_free(again);free(out);accepted++;}printf("VECTOR %s %s\n",r.name,r.ok?"ACCEPT":"REJECT");drop(&r);}CHECK(fgetc(f)==EOF);fclose(f);printf("METHOD c_blob_independent_schema_fields_and_rejection_slot_preservation PASS vectors=%u accept=%u reject=%u\n",n,accepted,rejected);printf("METHOD c_blob_own_inputs_encoder_error_and_tail_preservation PASS\n");}
static record named(const char*input,const char*name){FILE*f=fopen(input,"rb");CHECK(f);CHECK(fseek(f,8,SEEK_SET)==0);uint32_t n=rd32(f);for(uint32_t i=0;i<n;i++){record r=load(f);if(strcmp(r.name,name)==0){fclose(f);return r;}drop(&r);}CHECK(0);fclose(f);record none;memset(&none,0,sizeof(none));return none;}
static void state(const char*input){record d=named(input,"action-0"),c=named(input,"action-1"),end=named(input,"action-3"),bad=named(input,"wrong-chunk-sha");mbt_receiver*r=NULL;CHECK(mbt_receiver_new(NULL,0,&r)==0);uint32_t kind=99;mbt_frame*receipt=(mbt_frame*)(uintptr_t)1;CHECK(mbt_receiver_accept(r,d.wire,d.wn,&kind,&receipt)==0&&kind==MBT_ACCEPT_DESCRIPTOR&&receipt==NULL);CHECK(mbt_receiver_accept(r,c.wire,c.wn,&kind,&receipt)==0&&kind==MBT_ACCEPT_RECEIPT);mbt_view v;CHECK(mbt_frame_view(receipt,&v,sizeof(v))==0&&v.status==MBT_ACCEPTED);mbt_frame_free(receipt);receipt=NULL;mbt_snapshot before,after;CHECK(mbt_receiver_snapshot(r,&before,sizeof(before))==0);CHECK(mbt_receiver_accept(r,c.wire,c.wn,&kind,&receipt)==0);CHECK(mbt_frame_view(receipt,&v,sizeof(v))==0&&v.status==MBT_EXISTING);mbt_frame_free(receipt);CHECK(mbt_receiver_snapshot(r,&after,sizeof(after))==0&&after.received_bytes==3&&after.next_sequence==2&&after.request_bytes>before.request_bytes&&after.response_bytes>before.response_bytes);kind=99;receipt=(mbt_frame*)(uintptr_t)1;CHECK(mbt_receiver_accept(r,bad.wire,bad.wn,&kind,&receipt)==MBT_DIGEST&&kind==99&&receipt==(mbt_frame*)(uintptr_t)1);CHECK(mbt_receiver_accept(r,end.wire,end.wn,&kind,&receipt)==0&&kind==MBT_ACCEPT_VERIFIED_BYTES&&receipt==NULL);CHECK(mbt_receiver_snapshot(r,&after,sizeof(after))==0&&after.phase==MBT_VERIFIED_BYTES&&after.retained_recent_requests==0);mbt_receiver_free(r);printf("METHOD c_blob_streamed_hash_exact_duplicate_and_failure_output_preservation PASS\n");CHECK(mbt_receiver_new(NULL,0,&r)==0);CHECK(mbt_receiver_accept(r,d.wire,d.wn,&kind,&receipt)==0);CHECK(mbt_receiver_cancel(r)==0);CHECK(mbt_receiver_snapshot(r,&before,sizeof(before))==0&&before.phase==MBT_PHASE_CANCELLED);CHECK(mbt_receiver_accept(r,c.wire,c.wn,&kind,&receipt)==MBT_CANCELLED);CHECK(mbt_receiver_snapshot(r,&after,sizeof(after))==0&&memcmp(&before,&after,sizeof(before))==0);mbt_receiver_free(r);printf("METHOD c_blob_cancel_keeps_fees_and_closes_receiver PASS\n");drop(&d);drop(&c);drop(&end);drop(&bad);}
#ifndef C06_BLOB_CPP
int main(int argc,char**argv){CHECK(argc==2);corpus(argv[1]);state(argv[1]);return 0;}
#endif
