// Generated from the independent Rust UI fixture. Do not edit.
import 'package:morrow_plugin_ui/morrow_plugin_ui.dart';

final browserFormFixture = UiDocumentModel([
  UiNode(
    id: "root",
    parent: "",
    kind: Kind.column,
    label: "",
    text: "",
    action: "",
    enabled: true,
    checked: false,
    maxBytes: 0,
    tone: Tone.normal,
  ),
  UiNode(
    id: "heading",
    parent: "root",
    kind: Kind.text,
    label: "",
    text: "插件表单",
    action: "",
    enabled: true,
    checked: false,
    maxBytes: 0,
    tone: Tone.emphasis,
  ),
  UiNode(
    id: "title",
    parent: "root",
    kind: Kind.textInput,
    label: "标题",
    text: "灵感🌈",
    action: "title.edit",
    enabled: true,
    checked: false,
    maxBytes: 32,
    tone: Tone.normal,
  ),
  UiNode(
    id: "pinned",
    parent: "root",
    kind: Kind.toggle,
    label: "置顶",
    text: "",
    action: "pin.toggle",
    enabled: true,
    checked: false,
    maxBytes: 0,
    tone: Tone.normal,
  ),
  UiNode(
    id: "apply",
    parent: "root",
    kind: Kind.button,
    label: "应用",
    text: "",
    action: "apply",
    enabled: true,
    checked: false,
    maxBytes: 0,
    tone: Tone.normal,
  ),
]);
