"""Adapt optional int64 reflection without modifying Cap'n Proto wire code.

Upstream 0.1.0 metadata IDs are int, which cannot represent all uint64 values in
JavaScript. Keep native output intact; Web omits that optional reflection API.
Exact node IDs remain available as hexadecimal strings and BigInt in a sidecar.
Unknown generator shapes fail closed instead of rewriting arbitrary literals.
"""
import re

DECLARATION = re.compile(r"^const (?:Enum|Struct)SchemaInfo (\w+) = (?:Enum|Struct)SchemaInfo\(\n(.*?)^\);", re.M | re.S)
READER = re.compile(r"^  static const StructSchemaInfo schema = \w+;\n", re.M)
FACTORY = re.compile(r"^  @override\n  StructSchemaInfo get schema => \w+;\n", re.M)


def adapt(name: str, source: str) -> dict[str, str]:
    if not name.endswith(".capnp.dart"):
        raise ValueError("expected generated Cap'n Proto file")
    identities = {}
    for match in DECLARATION.finditer(source):
        identity = re.search(r"^  id: 0x([0-9a-fA-F]{16}),$", match[2], re.M)
        if identity is None or match[1] in identities:
            raise ValueError("unexpected reflection identity")
        identities[match[1]] = identity[1].lower()
    if not identities:
        raise ValueError("missing generated reflection")
    web = FACTORY.sub("", READER.sub("", DECLARATION.sub("", source)))
    if "SchemaInfo" in web or re.search(r"0x[0-9a-fA-F]{14,}", web):
        raise ValueError("unsupported metadata or large wire literal")
    refs = re.findall(r"(?:Struct|Enum)RefTypeSchemaInfo\(0x([0-9a-fA-F]{16})\)", source)
    if not set(value.lower() for value in refs).issubset(set(identities.values())):
        raise ValueError("external reflection reference needs explicit adaptation")
    stem = name[:-5]
    native_name = stem + ".native.dart"
    web_name = stem + ".web.dart"
    ids_name = stem + ".ids.dart"
    header = "// Generated by tool/generate_core_client.py; do not edit.\n"
    ids = header + "// Full unsigned schema IDs. Never convert these values to a JS int.\n"
    ids += "const schemaIds = <String, String>{\n"
    for key, value in identities.items():
        ids += f"  '{key}': '{value}',\n"
    ids += "};\nBigInt schemaId(String name) => BigInt.parse(schemaIds[name]!, radix: 16);\n"
    wrapper = header + f"export '{native_name}' if (dart.library.js_interop) '{web_name}';\nexport '{ids_name}';\n"
    web = header + "// Optional upstream int-based reflection is unavailable on Web.\n// Binary readers, builders, field offsets and schema validation are unchanged.\n" + web
    return {name: wrapper, native_name: source + "\nconst schemaReflectionAvailable = true;\n", web_name: web + "\nconst schemaReflectionAvailable = false;\n", ids_name: ids}
