"""Generate Dart bindings from the same Cap'n Proto schema Rust compiles."""
import hashlib, json, os, re, shutil, subprocess, tempfile, sys
from capnp_web_metadata import adapt
from pathlib import Path
from urllib.parse import urljoin, urlparse, unquote
ROOT=Path(__file__).resolve().parents[1]
CLIENT=ROOT/"packages/morrow_core_client"
def dart_executable():
    path=Path(os.environ.get("DART_BIN") or shutil.which("dart") or "dart")
    if path.suffix.lower()==".bat":
        candidate=path.parent/"cache/dart-sdk/bin/dart.exe"
        if candidate.exists(): return str(candidate)
    return str(path)
config=CLIENT/".dart_tool/package_config.json"
packages=json.loads(config.read_text(encoding="utf-8"))["packages"]
entry=next(p for p in packages if p["name"]=="capnpc_dart")
uri=urlparse(urljoin(config.as_uri(),entry["rootUri"]))
package_path=unquote(uri.path)
if os.name=="nt" and package_path.startswith("/"): package_path=package_path[1:]
generator=Path(package_path)/"bin/capnpc_dart.dart"
request=subprocess.check_output(["capnp","compile","-o-","--src-prefix=core/schemas","core/schemas/runtime.capnp","core/schemas/ui.capnp"],cwd=ROOT)
version=re.search(r"PROTOCOL_VERSION: u16 = ([0-9]+)", (ROOT/"core/src/runtime.rs").read_text()).group(1)
lines=["// Generated by tool/generate_core_client.py. Do not edit.",f"const protocolVersion = {version};"]
ui_version=re.search(r"VERSION: u16 = ([0-9]+)", (ROOT/"core/src/ui.rs").read_text()).group(1)
lines.append(f"const uiProtocolVersion = {ui_version};")
for name,path in [("runtimeDigest","runtime.capnp"),("contentDigest","content.proto"),("uiDigest","ui.capnp")]:
    digest=hashlib.sha256((ROOT/"core/schemas"/path).read_bytes().replace(b"\r\n",b"\n")).digest()
    lines.append("const "+name+" = <int>["+", ".join(map(str,digest))+"];")
with tempfile.TemporaryDirectory(prefix="core-codegen-",dir=ROOT/"build") as directory:
    subprocess.run([dart_executable(),"--packages="+str(config),str(generator)],input=request,cwd=directory,check=True)
    subprocess.run([dart_executable(),"format",directory],check=True,stdout=subprocess.DEVNULL)
    outputs = ["contract_identity.dart"]
    for name in ["runtime.capnp.dart", "ui.capnp.dart"]:
        original = (Path(directory)/name).read_text(encoding="utf-8")
        for filename, contents in adapt(name, original).items():
            (Path(directory)/filename).write_text(contents, encoding="utf-8")
            outputs.append(filename)
    (Path(directory)/"contract_identity.dart").write_text("\n".join(lines)+"\n",encoding="utf-8")
    subprocess.run([dart_executable(),"format",directory],check=True,stdout=subprocess.DEVNULL)
    for name in outputs:
        generated=(Path(directory)/name).read_text(encoding="utf-8")
        target=CLIENT/"lib/src/generated"/name
        if "--check" in sys.argv:
            if not target.exists() or target.read_text(encoding="utf-8")!=generated:
                raise SystemExit("Stale generated binding: "+str(target))
        else:
            target.write_text(generated,encoding="utf-8")
print("Verified generated bindings." if "--check" in sys.argv else "Generated typed bindings and fixed schema identity.")
