"""Local release evidence; a dirty-tree digest is not a Git commit or CI pass."""
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'reports/deep-review-build-2026-09-23.json'

def run(*args):
    return subprocess.check_output(args, cwd=ROOT, text=True, encoding='utf-8').strip()

def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

names = run('git', 'ls-files', '-co', '--exclude-standard').splitlines()
suffixes = {'.dart', '.rs', '.proto', '.capnp', '.toml', '.yaml', '.lock', '.json', '.py', '.ps1', '.cmake', '.cc', '.cpp', '.h', '.arb', '.frag'}
sources = {name: digest(ROOT / name) for name in sorted(set(names))
           if (ROOT / name).is_file() and (ROOT / name) != OUT
           and (Path(name).suffix in suffixes or Path(name).name == 'CMakeLists.txt')}
artifacts = [
    'build/windows-corners/x64/runner/Release/morrow_studio.exe',
    'build/windows-corners/x64/runner/Release/data/app.so',
    'build/windows-corners/x64/runner/Release/morrow-workbench-host.exe',
    'build/windows-corners/x64/runner/Release/morrow-migrate-library.exe',
    'build/windows-corners/x64/runner/Release/plugins/workbench.morrowplugin',
]
evidence = [
    'build/review-neumorphism-widgets.log',
    'build/review-neumorphism-glass.log',
    'build/review-neumorphism-visual-final.log',
    'build/review-neumorphism-analyze.log',
    'build/review-neumorphism-i18n-check.log',
    'build/review-migration-cli.log',
    'build/review-neumorphism-migration-windows.log',
    'build/review-neumorphism-migration-native.log',
    'build/review-migration-release-smoke.json',
    'test/goldens/neumorphic_controls_light.png',
    'test/goldens/neumorphic_controls_dark.png',
    'build/review-editor-draft-handoff-proposal-rust.log',
    'build/review-editor-draft-handoff-proposal-windows.log',
    'build/review-editor-draft-handoff-proposal-client.log',
    'build/review-ui-styles-widgets-final.log',
    'build/review-ui-styles-preferences.log',
    'build/review-ui-styles-native-final.log',
    'build/review-ui-styles-analyze.log',
    'build/review-ui-styles-i18n-check.log',
    'build/review-ui-styles-codegen-check.log',
    'build/review-ui-styles-windows-final.log',
    'build/review-full-tests.log', 'build/review-final-native.log',
    'build/review-core-client-tests-final.log', 'build/review-revision-rust.log',
    'build/review-cli-shutdown-final.log', 'build/review-preferences-evidence.log',
    'build/review-window-close.json', 'build/review-windows-final-build.log',
    'build/review-proposal-flutter-tests.log', 'build/review-proposal-native-final.log',
    'build/review-proposal-tests.log', 'build/review-proposal-analyze.log',
    'build/review-proposal-windows-final-build.log',
    'build/review-recovery-dialog-tests.log', 'build/review-recovery-abandon-tests.log',
    'build/review-recovery-ui-flutter-tests.log', 'build/review-recovery-ui-analyze.log',
    'build/review-recovery-ui-windows-final.log', 'build/review-recovery-ui-native-final.log',
    'build/review-tasks-v2-native.log', 'build/review-tasks-v2-guest.log',
    'build/review-tasks-v2-wasm-build.log', 'build/review-tasks-v2-windows.log',
    'build/review-tasks-v2-legacy-regression.log',
    'build/review-content-migrations-core.log',
    'build/review-content-migrations-host.log', 'build/review-content-migrations-wasm-check.log',
    'build/review-content-migrations-windows.log', 'build/review-content-migrations-native.log',
    'build/review-versioned-content-core.log', 'build/review-versioned-content-wasm.log',
    'build/review-tasks-migration-combined-host.log',
    'build/review-versioned-content-windows.log',
    'build/review-late-content-flutter.log', 'build/review-late-content-native.log',
    'build/review-tasks-edit-projection.log', 'build/review-tasks-edit-host.log',
    'build/review-tasks-owner.log', 'build/review-tasks-edit-legacy.log',
    'build/review-tasks-owner-windows.log', 'build/review-tasks-owner-native.log',
    'build/review-cards-v2-plugin.log', 'build/review-cards-v2-wasm.log',
    'build/review-cards-edit-projection.log', 'build/review-cards-edit-host.log',
    'build/review-cards-owner.log', 'build/review-cards-legacy.log',
    'build/review-cards-windows.log', 'build/review-cards-native.log',
    'build/review-query-v2-plugin.log', 'build/review-query-v2-wasm.log',
    'build/review-query-v2-plans-final.log', 'build/review-query-v2-capture-final.log',
    'build/review-query-v2-windows.log', 'build/review-query-v2-native.log',
    'build/review-content-api-rust.log', 'build/review-content-api-protocol.log',
    'build/review-versioned-content-codec.log', 'build/review-content-api-native.log',
    'build/review-content-api-analyze-final.log', 'build/review-content-api-codegen.log',
    'build/review-content-api-windows-final.log',
    'build/review-captured-cards-projection.log',
    'build/review-captured-cards-owner.log',
    'build/review-captured-cards-legacy.log',
    'build/review-captured-cards-native.log',
    'build/review-captured-cards-analyze-final.log',
    'build/review-captured-cards-codegen.log',
    'build/review-captured-cards-windows.log',
    'build/review-versioned-workspace-tests.log',
    'build/review-versioned-workspace-analyze.log',
    'build/review-versioned-workspace-windows.log',
    'build/review-mixed-ui-widget.log',
    'build/review-mixed-ui-native-final.log',
    'build/review-mixed-ui-analyze.log',
    'build/review-mixed-ui-i18n.log',
    'build/review-mixed-ui-i18n-tests.log',
    'build/review-mixed-ui-windows.log',
    'build/review-no-commit-rust.log',
    'build/review-no-commit-native.log',
    'build/review-no-commit-native-final.log',
    'build/review-no-commit-analyze.log',
    'build/review-no-commit-windows-final.log',
    'build/review-editor-recovery-rust9.log',
    'build/review-editor-recovery-native.log',
    'build/review-editor-recovery-final-tests.log',
    'build/review-editor-recovery-client-analyze.log',
    'build/review-editor-recovery-codegen.log',
    'build/review-editor-recovery-i18n.log',
    'build/review-editor-recovery-i18n-tests.log',
    'build/review-editor-recovery-windows-final.log',
    'build/review-editor-drafts-final-tests.log',
    'build/review-editor-drafts-analyze-final.log',
    'build/review-editor-drafts-i18n-tests.log',
    'build/review-editor-drafts-i18n-check.log',
    'build/review-editor-drafts-windows-final.log',
    'build/review-editor-draft-coexistence-native-final.log',
    'build/review-editor-draft-unit-final.log',
    'build/review-editor-draft-recovery-final.log',
    'build/review-editor-draft-clippy.log',
    'build/review-editor-draft-journal-windows.log',
    'build/review-editor-draft-journal-client-final.log',
    'build/review-editor-draft-protocol-check.log',
    'build/review-editor-draft-protocol-unit.log',
    'build/review-editor-draft-protocol-rust.log',
    'build/editor_draft_codec_test.log',
    'build/editor_draft_codec_analyze.log',
    'build/review-editor-draft-protocol-analyze.log',
    'build/review-editor-draft-protocol-codegen.log',
    'build/review-editor-draft-protocol-windows.log',
    'build/review-editor-draft-transfer-regression.log',
    'build/review-editor-draft-protocol-host-regression.log',
    'build/review-editor-draft-protocol-client-final.log',
    'build/review-editor-draft-protocol-native-injection-mismatch.log',
    'build/review-editor-draft-session-combined.log',
    'build/review-editor-draft-binding-test.log',
    'build/review-editor-draft-session-client-missing-import.log',
    'build/review-editor-draft-session-client-final.log',
    'build/review-editor-draft-session-analyze.log',
    'build/review-editor-draft-session-windows.log',
    'build/review-editor-draft-new-card-lib.log',
    'build/review-editor-draft-new-card-rust.log',
    'build/review-editor-draft-new-card-unit.log',
    'build/review-editor-draft-new-card-client.log',
    'build/review-editor-draft-new-card-analyze.log',
    'build/review-editor-draft-new-card-windows.log',
    'build/review-editor-draft-new-card-codegen.log',
    'build/review-core-retained-staging-lib.log',
    'build/review-core-retained-staging-tests.log',
    'build/review-core-retained-staging-windows.log',
    'build/review-core-retained-staging-client.log',
    'build/review-editor-draft-staging-check.log',
    'build/review-editor-draft-staging-host-first.log',
    'build/review-editor-draft-staging-host.log',
    'build/review-editor-draft-staging-capacity.log',
    'build/review-editor-draft-staging-windows.log',
    'build/review-editor-draft-staging-client.log',
    'build/review-editor-draft-staging-api-check.log',
    'build/review-editor-draft-staging-api-unit.log',
    'build/review-editor-draft-import-codegen.log',
    'build/review-editor-draft-import-codegen-check.log',
    'build/review-editor-draft-import-gates.log',
    'build/review-editor-draft-import-rust.log',
    'build/review-editor-draft-import-dart.log',
    'build/review-editor-draft-import-windows.log',
    'build/review-editor-draft-import-client.log',
    'build/review-editor-draft-import-analyze.log',
    'build/review-editor-draft-decision-rust-final.log',
    'build/review-editor-draft-import-decision-wire.log',
    'build/review-editor-draft-import-decision-route.log',
    'build/review-editor-draft-decision-codegen.log',
    'build/review-editor-draft-decision-codegen-check.log',
    'build/review-editor-draft-decision-windows.log',
    'build/review-editor-draft-decision-client-final.log',
    'build/review-editor-draft-decision-process-seed.log',
    'build/review-editor-draft-decision-process-recover.log',
    'build/review-editor-draft-decision-analyze.log',
    'build/review-editor-draft-scopes-dart-tests.log',
    'build/review-editor-draft-scopes-dart-analyze.log',
    'build/review-editor-draft-recovery-selection.log',
    'build/review-editor-draft-recovery-ui-pure-final.log',
    'build/review-editor-draft-recovery-ui-final.log',
    'build/review-editor-draft-ownership-combined.log',
    'build/review-editor-draft-ownership-final.log',
    'build/review-editor-draft-ownership-analyze-final.log',
    'build/review-editor-draft-ownership-windows.log',
    'build/review-editor-draft-handoff-initial.log',
    'build/review-editor-draft-handoff-boundaries-initial.log',
    'build/review-editor-draft-handoff-final.log',
    'build/review-editor-draft-handoff-regression.log',
    'build/review-editor-draft-handoff-unit.log',
    'build/review-editor-draft-handoff-windows.log',
    'build/review-editor-draft-handoff-client.log',
    'build/review-editor-draft-handoff-wire-unit.log',
    'build/review-editor-draft-handoff-wire-rust.log',
    'build/review-editor-draft-handoff-wire-codec.log',
    'build/review-editor-draft-handoff-wire-native-initial.log',
    'build/review-editor-draft-handoff-wire-native-final.log',
    'build/review-editor-draft-handoff-wire-analyze.log',
    'build/review-editor-draft-handoff-wire-codegen.log',
    'build/review-editor-draft-handoff-wire-codegen-check.log',
    'build/review-editor-draft-handoff-wire-windows.log',
    'build/review-editor-draft-handoff-wire-windows-final.log',
    'build/review-editor-draft-handoff-wire-final-client.log',
    'build/review-editor-draft-recovery-ui-analyze-final.log',
    'build/review-editor-draft-recovery-ui-i18n-tests.log',
    'build/review-editor-draft-recovery-ui-i18n-check.log',
    'build/review-editor-draft-recovery-ui-windows-final.log',
]
value = {
    'version': 1,
    'head': run('git', 'rev-parse', 'HEAD'),
    'branch': run('git', 'branch', '--show-current'),
    'dirty': bool(run('git', 'status', '--porcelain')),
    'source_digest': hashlib.sha256(json.dumps(sources,sort_keys=True,separators=(',', ':')).encode()).hexdigest(),
    'source_files': sources,
    'build': {'platform':'windows-x64','mode':'Release','target':'lib/main_rust.dart',
              'directory':'build/windows-corners/x64','application_version':'0.1.9-test.54+58',
              'plugin_public_abi_changed':False, 'ci_run':False,
              'ui_style_follow':'Flat default and Neumorphism; glass/motion/context menus; acyclic branched component material inheritance; 37 widget, 12 plugin Rust and 7 native-client tests passed; Windows Release rebuilt; no performance or other-platform qualification',
              'neumorphism_polish_and_migration':'Raised and inset controls, collapsed style picker; dual-format copy-first Windows CLI; 44 UI, 8 migration and 4 final native-client tests passed; 14 Dart targets clean, i18n checked; Release CLI smoke imported JSON then migrated SQLite again; no real user libraries or new platform/performance qualification',
              'private_content_api':'content_api.capnp v1; typed V1/V2 reads, mutations, query pagination; FinishCapturedCard common editor provenance with durable original proposal recovery and abandonment tombstone; mixed workspace with TaskId UI and captured editor; in-window S1/S2 draft coexistence with exact successor scope and canonical attachment rebase; S2 UI persistence and migration entry not enabled',
              'editor_draft_journal':'Host Rust journal plus private Capnp and Dart native client: generation CAS, exact historical retries, raw valid-Unicode editor values and scoped attachment pins, bounded 8 MiB transfer with exact lost-reply cleanup; independent Dart draft session/debounce and full TextEditingValue binding plus verified S1 evidence handoff implemented; explicit existing/new-card origins and blank new-card initialization implemented and tested without business creation; default editor autosave, lineage transitions, recovery UI and history maintenance pending; durable staging implemented in host Rust library, typed private wire and Dart adapter/session implemented; durable abandonment decision recovery and inactive-scope discovery verified across independent client processes; attachment decision recovery UI integrated with serialized discovery; workspace session leases, bounded close preparation, explicit asset catalog and confirmed-pin adoption verified with 60 client/native tests; host durable parent-child handoff and conditional retirement verified (89 Rust checks, 7 native-client regressions); private handoff wire/Dart complete with host request digests, serialized transfers and paged lineage discovery, verified by 44 Rust and 22 client checks; Rust host durable handoff proposals with immutable prepare, inspect/list, complete/retire/cancel and legacy guards verified by 50 Rust and 13 existing native-client regressions; three independent Rust processes recover Prepared and ChildCommitted requests without caller objects; new proposal private wire/Dart and full editor autosave/source handoff pending; strict Clippy not cleared',
              'retained_staging_core':'Atomic blob plus releasable Snapshot owner; exact verified owner retry is read-only; restart lookup rejects ambiguous or corrupt owner and preserves valid unknown metadata; host durable import operation/state integrated; typed private wire integrated; durable abandonment decision restoration verified across independent client processes; attachment decision recovery UI integrated; full editor autosave/source handoff pending',
              'durable_draft_import_host':'Metadata-only audited Pending/Ready/Retired imports; stable scoped identity; exact retained-byte retries; atomic draft consumption markers; distinct explicit abandon versus automatic retirement; recoverable Snapshot release/prune with reserved revision capacity; typed private actions 102-113, durable abandonment decisions with original-op cancellation, exact legacy committed receipts, paged inactive-scope discovery and Dart immutable sessions integrated; host 59 integration tests, final Windows client 34 tests passed, five scenarios seeded/recovered in separate client processes; serialized discovery and nine-locale workspace recovery UI integrated; final UI/client combined 68 tests passed; full editor autosave and long-term history maintenance pending',
              'first_party_package_version':'0.1.9-test.54.4',
              'first_party_query_contract':'morrow.workbench.query.request.v2 (new mixed query; V1 replay unchanged)',
              'first_party_cards_contract':'morrow.workbench.cards.request.v2 (new; V1 and tasks V2 unchanged)',
              'first_party_tasks_contract':'morrow.workbench.tasks.request.v2 (new; V1 unchanged)',
              'android_build':'NotRun','other_native_platforms':'NotRun'},
    'tools': {'rust':run('rustc','--version'),'cargo':run('cargo','--version'),
              'dart':run('C:/flutter/bin/cache/dart-sdk/bin/dart.exe','--version'),
              'flutter_cache':json.loads((Path('C:/flutter/bin/cache/flutter.version.json')).read_text())},
    'artifacts': {name:{'sha256':digest(ROOT/name),'bytes':(ROOT/name).stat().st_size} for name in artifacts},
    'evidence': {name:digest(ROOT/name) for name in evidence},
    'qualification': 'See deep-review-ruling-2026-09-23.md; codec, store, real process and platform evidence have separate scopes.',
}
OUT.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Wrote {OUT.relative_to(ROOT)}: {len(sources)} source/config digests, {len(artifacts)} artifacts')
