const standardAudioExtensions = [
  'mp3',
  'wav',
  'flac',
  'm4a',
  'aac',
  'ogg',
  'opus',
  'wma',
  'ape',
  'aif',
  'aiff',
  'alac',
  'wv',
  'dsf',
  'dff',
  'mp2',
  'ac3',
  'dts',
  'au',
];
const containerAudioFormats = <String, int>{
  'ncm': 1,
  'kgm': 3,
  'kgma': 3,
  'kgg': 3,
  'vpr': 3,
  'kwm': 4,
  'tm0': 5,
  'tm2': 5,
  'tm3': 5,
  'tm6': 5,
  'xm': 0,
  'x2m': 7,
  'x3m': 7,
  'qmc0': 2,
  'qmc2': 2,
  'qmc3': 2,
  'qmc4': 2,
  'qmc6': 2,
  'qmc8': 2,
  'qmcflac': 2,
  'qmcogg': 2,
  'tkm': 2,
  'bkcmp3': 2,
  'bkcm4a': 2,
  'bkcflac': 2,
  'bkcwav': 2,
  'bkcape': 2,
  'bkcogg': 2,
  'bkcwma': 2,
  '666c6163': 2,
  '6d7033': 2,
  '6f6767': 2,
  '6d3461': 2,
  '776176': 2,
  'mmp4': 2,
  'mgg': 2,
  'mgg0': 2,
  'mgg1': 2,
  'mgga': 2,
  'mggh': 2,
  'mggl': 2,
  'mggm': 2,
  'mflac': 2,
  'mflac0': 2,
  'mflac1': 2,
  'mflaca': 2,
  'mflach': 2,
  'mflacl': 2,
  'mflacm': 2,
};
const maxMusicBytes = 150 * 1024 * 1024;
String audioExtension(String name) => name.toLowerCase().split('.').last;
String audioImportError(int code) => switch (code) {
  6 => '此音频需要额外密钥，暂时无法导入。请使用可直接播放的音频文件。',
  4 || 5 => '暂不支持此音频的格式或版本。',
  10 => '音频过大，请选择 150 MB 以内的文件。',
  255 => '音频读取组件暂不可用，请重试。',
  _ => '无法读取此音频，文件可能不完整或格式暂不支持。',
};
String decodedAudioName(String name, String extension) {
  final basename = name.replaceAll('\\', '/').split('/').last;
  final dot = basename.lastIndexOf('.');
  final stem = dot < 0 ? basename : basename.substring(0, dot);
  return '$stem.${extension == 'mp4' ? 'm4a' : extension}';
}
