// This file is @generated by prost-build.
/// Host-local persistence only; not a guest IPC or restorable live authority.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Profile {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub identity: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub slot: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub core_identity_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub lock_namespace: ::prost::alloc::string::String,
    /// profile copies/relocations are not restorable owner domains
    #[prost(string, tag = "6")]
    pub canonical_root: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Approval {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub profile: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub slot: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub plugin_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub operation: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub artifact_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "10")]
    pub config_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "11")]
    pub schema_sha256: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "12")]
    pub generation: u64,
    #[prost(uint64, tag = "13")]
    pub capabilities: u64,
    #[prost(uint64, tag = "14")]
    pub lifetime_ms: u64,
    /// diagnostics only; never renews Instant deadline
    #[prost(uint64, tag = "15")]
    pub approved_unix_ms: u64,
    /// 1 approved,2 consumed,3 revoked,4 expired
    #[prost(uint32, tag = "16")]
    pub state: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Owner {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(string, tag = "2")]
    pub grant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub generation: u64,
    #[prost(string, tag = "5")]
    pub phase: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub child_pid: u32,
    #[prost(uint64, tag = "7")]
    pub session: u64,
    #[prost(uint64, tag = "8")]
    pub epoch: u64,
    #[prost(bool, tag = "9")]
    pub exit_observed: bool,
    #[prost(bool, tag = "10")]
    pub stdout_eof: bool,
    #[prost(bool, tag = "11")]
    pub stderr_eof: bool,
    #[prost(bytes = "vec", tag = "12")]
    pub snapshot_sha256: ::prost::alloc::vec::Vec<u8>,
}
