#define _CRT_SECURE_NO_WARNINGS
#include "morrow_fs_directory_v1.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#define CHECK(x) do{if(!(x)){fprintf(stderr,"FAIL %d %s\n",__LINE__,#x);exit(1);}}while(0)
typedef struct record{char*name;uint32_t ok,wn,count,terminal;uint64_t seq;mfd_entry_view_v1*entries;uint8_t*wire;}record;
static uint32_t rd32(FILE*f){uint8_t b[4];CHECK(fread(b,1,4,f)==4);return(uint32_t)b[0]|((uint32_t)b[1]<<8)|((uint32_t)b[2]<<16)|((uint32_t)b[3]<<24);}
static uint64_t rd64(FILE*f){uint64_t a=rd32(f),b=rd32(f);return a|(b<<32);}
static void*alloc(size_t n){void*p=malloc(n?n:1);CHECK(p);return p;}
static record load(FILE*f){record r;uint32_t n=rd32(f);r.ok=rd32(f);r.wn=rd32(f);r.count=rd32(f);r.terminal=rd32(f);CHECK(rd32(f)==0);r.seq=rd64(f);CHECK(n<256&&r.wn<=70000&&r.count<=33);r.name=(char*)alloc((size_t)n+1);CHECK(fread(r.name,1,n,f)==n);r.name[n]=0;r.entries=(mfd_entry_view_v1*)alloc((size_t)r.count*sizeof(*r.entries));for(uint32_t i=0;i<r.count;i++){mfd_entry_view_v1*e=r.entries+i;memset(e,0,sizeof(*e));CHECK(fread(e->entry_id,1,32,f)==32);e->name_length=rd32(f);e->encoding=rd32(f);e->kind=rd32(f);e->has_logical_length=rd32(f);e->logical_length=rd64(f);CHECK(e->name_length<=20000);uint8_t*name=(uint8_t*)alloc(e->name_length);CHECK(fread(name,1,e->name_length,f)==e->name_length);e->name=name;}r.wire=(uint8_t*)alloc(r.wn);CHECK(fread(r.wire,1,r.wn,f)==r.wn);return r;}
static void drop(record*r){for(uint32_t i=0;i<r->count;i++)free((void*)r->entries[i].name);free(r->entries);free(r->name);free(r->wire);}
static void fields(const mfd_page_v1*h,const record*r){mfd_page_view_v1 v;CHECK(mfd_page_v1_view(h,&v,sizeof(v))==0&&v.abi_version==1&&v.struct_size==sizeof(v)&&v.reserved==0&&v.page_sequence==r->seq&&v.entry_count==r->count&&v.terminal==r->terminal);for(int i=0;i<32;i++)CHECK(v.selection_epoch[i]==1);for(uint32_t i=0;i<r->count;i++){mfd_entry_view_v1 e;const mfd_entry_view_v1*x=r->entries+i;CHECK(mfd_page_v1_entry(h,i,&e,sizeof(e))==0);CHECK(e.reserved==0&&memcmp(e.entry_id,x->entry_id,32)==0&&e.name_length==x->name_length&&e.encoding==x->encoding&&e.kind==x->kind&&e.has_logical_length==x->has_logical_length&&e.logical_length==x->logical_length);CHECK(e.name_length==0||memcmp(e.name,x->name,x->name_length)==0);}mfd_entry_view_v1 e,before;memset(&e,0xa5,sizeof(e));memcpy(&before,&e,sizeof(e));CHECK(mfd_page_v1_entry(h,r->count,&e,sizeof(e))!=0&&memcmp(&e,&before,sizeof(e))==0);}
static void corpus(const char*input){FILE*f=fopen(input,"rb");CHECK(f);uint8_t magic[8];CHECK(fread(magic,1,8,f)==8&&memcmp(magic,"DRCV0001",8)==0);uint32_t n=rd32(f),accepted=0,rejected=0;for(uint32_t i=0;i<n;i++){record r=load(f);mfd_page_v1*h=(mfd_page_v1*)(uintptr_t)1;uint32_t rc=mfd_page_v1_decode(r.wire,r.wn,&h);if((rc==0)!=(r.ok!=0)){fprintf(stderr,"VERDICT %s status=%u expected=%u\n",r.name,rc,r.ok);exit(1);}if(!r.ok){CHECK(h==(mfd_page_v1*)(uintptr_t)1);rejected++;}else{fields(h,&r);memset(r.wire,0xaa,r.wn);fields(h,&r);mfd_page_view_v1 v;CHECK(mfd_page_v1_view(h,&v,sizeof(v))==0);mfd_page_v1*copy=NULL;CHECK(mfd_page_v1_create(&v,sizeof(v),&copy)==0);uint8_t*out=(uint8_t*)alloc(65536);memset(out,0xa5,65536);uint32_t length=0xdeadbeef;CHECK(mfd_page_v1_encode(h,out,1,&length)==MFD_BUFFER&&length==0xdeadbeef&&out[0]==0xa5);CHECK(mfd_page_v1_encode(h,out,65536,&length)==0);for(uint32_t j=length;j<65536;j++)CHECK(out[j]==0xa5);mfd_page_v1*again=NULL;CHECK(mfd_page_v1_decode(out,length,&again)==0);fields(again,&r);mfd_page_v1_free(h);fields(copy,&r);mfd_page_v1_free(copy);mfd_page_v1_free(again);free(out);accepted++;}printf("VECTOR %s %s\n",r.name,r.ok?"ACCEPT":"REJECT");drop(&r);}CHECK(fgetc(f)==EOF);fclose(f);printf("METHOD c_directory_independent_fields_ownership_and_rejected_output_slots PASS vectors=%u accept=%u reject=%u\n",n,accepted,rejected);printf("METHOD c_directory_encoder_errors_entry_index_and_tail_preservation PASS\n");}
static record named(const char*input,const char*name){FILE*f=fopen(input,"rb");CHECK(f);CHECK(fseek(f,8,SEEK_SET)==0);uint32_t n=rd32(f);for(uint32_t i=0;i<n;i++){record r=load(f);if(strcmp(r.name,name)==0){fclose(f);return r;}drop(&r);}CHECK(0);fclose(f);record r;memset(&r,0,sizeof(r));return r;}
static void state(const char*input){record p=named(input,"file-no-length");uint8_t epoch[32];memset(epoch,1,32);mfd_state_v1*s=NULL;mfd_state_limits_v1 defaults;memset(&defaults,0,sizeof(defaults));defaults.abi_version=1;defaults.struct_size=sizeof(defaults);defaults.max_entries=1024;defaults.max_pages=1024;defaults.max_name_bytes=1048576;defaults.max_wire_bytes=1048576;CHECK(mfd_state_v1_new(epoch,&defaults,sizeof(defaults),&s)==0);mfd_page_v1*page=NULL;CHECK(mfd_state_v1_admit(s,p.wire,p.wn,&page)==0);mfd_page_v1_free(page);mfd_state_snapshot_v1 before,after;CHECK(mfd_state_v1_snapshot(s,&before,sizeof(before))==0&&before.resident_ids==1&&before.terminal==1);page=(mfd_page_v1*)(uintptr_t)1;CHECK(mfd_state_v1_admit(s,p.wire,p.wn,&page)==MFD_TERMINAL&&page==(mfd_page_v1*)(uintptr_t)1);CHECK(mfd_state_v1_snapshot(s,&after,sizeof(after))==0&&after.accepted_pages==before.accepted_pages&&after.admitted_wire_bytes>before.admitted_wire_bytes);uint64_t paid=after.admitted_wire_bytes;CHECK(mfd_state_v1_release(s)==0);CHECK(mfd_state_v1_snapshot(s,&after,sizeof(after))==0&&after.resident_ids==0&&after.released==1&&after.admitted_wire_bytes==paid);CHECK(mfd_state_v1_admit(s,p.wire,p.wn,&page)==MFD_RELEASED);mfd_state_v1_free(s);printf("METHOD c_directory_terminal_failures_and_release_preserve_admission_charge PASS\n");mfd_state_limits_v1 l;memset(&l,0,sizeof(l));l.abi_version=1;l.struct_size=sizeof(l);l.max_entries=1024;l.max_pages=1024;l.max_name_bytes=1048576;l.max_wire_bytes=p.wn-1;CHECK(mfd_state_v1_new(epoch,&l,sizeof(l),&s)==0);CHECK(mfd_state_v1_snapshot(s,&before,sizeof(before))==0);CHECK(mfd_state_v1_admit(s,p.wire,p.wn,&page)==MFD_BUDGET);CHECK(mfd_state_v1_snapshot(s,&after,sizeof(after))==0&&memcmp(&before,&after,sizeof(before))==0);mfd_state_v1_free(s);printf("METHOD c_directory_budget_refusal_preserves_full_snapshot PASS\n");drop(&p);}
#ifndef C06_DIRECTORY_CPP
int main(int argc,char**argv){CHECK(argc==2);corpus(argv[1]);state(argv[1]);return 0;}
#endif
